### ISSUE TITLE
Refactor GW-Proxy lambda code (saas_vps.py) into separate file

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/gw-proxy-serverless#1]
see code here 

https://github.com/filetrust/GW-Bot/blob/master/gw_bot/lambdas/gw/proxy/saas_vps.py

which you can see in action here:
 - https://gw-proxy.com/
 - https://glasswall.gw-proxy.com/
 - https://stackoverflow.gw-proxy.com/
 - https://bae_systems_com.gw-proxy.com/

**Comment by atykhonov** [comment]
https://glasswall.gw-proxy.com/, https://bae_systems_com.gw-proxy.com/ and https://stackoverflow.gw-proxy.com/ returns privacy error:

```
Your connection is not private
Attackers might be trying to steal your information from glasswall.gw-proxy.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```

this is probably because of https misconfiguration let me know please whether this is something that I can work on and fix.

**Comment by atykhonov** [comment]
I refactored the code, please see https://github.com/filetrust/GW-Bot/pull/4. If it looks good, please let's merge it first of all. If there is a need to move the code (to this or any other repository) then please let's do it after review/merge.
