### ISSUE TITLE
Add compression support to gw-bot

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/gw-proxy-serverless#12]
which is what I believe is causing this when accessing google.com via the proxy: https://google_com.gw-proxy.com/

![image](https://user-images.githubusercontent.com/656739/75399362-ed509580-58f3-11ea-9374-91db13e5c74e.png)

**Comment by manish2kcoder** [comment]
Deployed a api gateway and put saas_vps in a lambda behind it in my aws account. Created a layer to load requests. Made some minor code changes to get it working. Was able to reproduce the issue.
The response from google has content-type as application/html but the body is encoded. Need to find out what this encoding it. Does not look like a normal gzip encoding as it does not open when downloaded as a plain zip.

**Comment by manish2kcoder** [comment]
We have found the issue is with brotli encoding (Content-Encoding br).Check this now it renders google properly
https://dkh8hq0cja.execute-api.us-east-1.amazonaws.com/test/
I will now update the latest source code with the fix and add a few test cases around it. And perform tests with other sites e.g glasswall, stackoverflow etc so that the fix does not break anything

**Comment by DinisCruz** [comment]
https://www.projectsend.org also shows the same behaviour

`python3 bin/local-server.py https://www.projectsend.org 2222`

![image](https://user-images.githubusercontent.com/656739/75635960-61e84480-5c12-11ea-861d-32c4e8e8e609.png)

**Comment by manish2kcoder** [comment]
I will test https://www.projectsend.org before submitting

**Comment by manish2kcoder** [comment]
for an update . all code and tests for https://github.com/filetrust/gw-proxy-serverless/issues/12 is here https://github.com/manish2kcoder/gw-proxy-serverless. I still need to run proxy locally and test end to end with it as suggested in the  bug by dinis

**Comment by DinisCruz** [comment]
@manish2kcoder can you send a Pull Request (PR) so that I can review it?

Without a PR I don't don't know where to look at

**Comment by tstepany** [comment]
https://github.com/filetrust/gw-proxy-serverless/pull/64

**Comment by manish2kcoder** [comment]
Tested  https://www.projectsend.org, it works.
Check below
https://dkh8hq0cja.execute-api.us-east-1.amazonaws.com/test/

![image](https://user-images.githubusercontent.com/12497914/75974952-ad923b00-5efd-11ea-8d5f-2d6cacddcf23.png)
