### ISSUE TITLE
Add POST support to GW-Proxy

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/gw-proxy-serverless#3]
https://github.com/filetrust/GW-Bot/blob/master/gw_bot/lambdas/gw/proxy/saas_vps.py currently only supports get

Do be done in sync with #1

**Comment by DinisCruz** [comment]
Hi, any updates on this?

**Comment by manish2kcoder** [comment]
Development for adding post support is complete. Working on writing tests for this

**Comment by manish2kcoder** [comment]
Added tests for Post request
