### ISSUE TITLE
bug - figure out why requests didn't work when installed from github actions

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/gw-proxy-serverless#31]
when I put requests here it didn't work

![image](https://user-images.githubusercontent.com/656739/75616642-84fbf100-5b4b-11ea-98cb-2f84152ab758.png)

but when I put here it did

![image](https://user-images.githubusercontent.com/656739/75616646-9218e000-5b4b-11ea-998d-c376f25c35ea.png)

Here is the action where it didn't work (before adding to docker) https://github.com/filetrust/gw-proxy-serverless/runs/477227044?check_suite_focus=true

Here is the action where it worked: https://github.com/filetrust/gw-proxy-serverless/runs/477229825?check_suite_focus=true

**Comment by atykhonov** [comment]
Take a look please at this PR https://github.com/filetrust/gw-proxy-serverless/pull/44 (where all the checks have passed). I removed `requests` from `Dockerfile` and `requirements.txt` and this works well.

Is this issue still actual?
