### ISSUE TITLE
BUG: The latest version of the Proxy, it is throwing a weird error with HttpServer It is basically hanging after a couple requests

### ISSUE THREAD

**Issue by tstepany** [filetrust/gw-proxy-serverless#46]
BUG: Can a couple of devs here take a look at the latest version of the Proxy, it is throwing a weird error with HttpServer
It is basically hanging after a couple requests

![image (9)](https://user-images.githubusercontent.com/10744307/75684240-ad453600-5c98-11ea-825a-4412923f7365.png)

**Comment by DinisCruz** [comment]
no need to fix since we are going to move away from this python API
